convert head/lib
EOSIO/demux-js-eos pull request #65
Opened 2019-03-20 20:46 UTC by masaka3620

The data coming out of Postgres needs to be converted to integers to allow demux to continue when it reaches what it thinks the current head block is.

2019-03-20 20:52 UTC, chris-allnutt reviewed
Is parseint sufficient for blocknumber? If I remember we didn't use ints because at some point it will truncate the number.

2019-03-20 21:05 UTC, jeffreyssmith2nd requested changes

2019-03-20 21:05 UTC, jeffreyssmith2nd commented on src/state-history/StateHistoryPostgresActionReader.ts
> +    return parseInt(statusRow.head)
This should actually be `Number(statusRow.head)`

2019-03-20 21:05 UTC, jeffreyssmith2nd commented on src/state-history/StateHistoryPostgresActionReader.ts
> +    return parseInt(statusRow.irreversible)
same here

2019-03-20 21:12 UTC, chris-allnutt approved these changes

2019-03-21 13:13 UTC, jeffreyssmith2nd approved these changes
Looks good, thanks 👍

2019-03-21 13:49 UTC, merged